apiVersion: portaltransporter.infrared.reddit.com/v1alpha1
kind: BackendLBPolicies
metadata:
  name: blbp-invalidpolicy
  namespace: default
spec:
  backendRef:
    group: ''
    kind: Service
    name: ingress-probe-responder-grpc
    version: v1
  supportedPolicies: