# Modified version of health. Guessing this will degraded but limited api information.
apiVersion: portaltransporter.infrared.reddit.com/v1alpha1
kind: BackendLBPolicies
metadata:
  generation: 1
  name: blbp-degrade
spec:
  backendRef:
    group: ''
    kind: invalid
    name: ingress-probe-responder-grpc
    version: v1
  supportedPolicies:
  - clientSideWeightedRoundRobinPolicy:
      blackoutPeriod: 10s
      errorUtilizationPenalty: '0'
      weightExpirationPeriod: 3m
      weightUpdatePeriod: 1s
status:
  parents:
  - conditions:
    - lastTransitionTime: '2025-06-03T19:57:10Z'
      message: "backendRef.kind 'invalid' is not a supported kind (only 'Service' allowed)" 
      observedGeneration: 1
      reason: NotReconciled
      status: 'False'
      type: Available
    controllerName: transport.infrared.reddit.com/portal-transporter