# Based off this: https://kube-web-view.build.ue1.snooguts.net/clusters/prod-3-d/namespaces/ingress-probe-responder/backendlbpolicies/ingress-probe-responder-grpc?
apiVersion: portaltransporter.infrared.reddit.com/v1alpha1
kind: BackendLBPolicies
metadata:
  generation: 1
  name: blbp-healthy
spec:
  backendRef:
    group: ''
    kind: Service
    name: ingress-probe-responder-grpc
    version: v1
  supportedPolicies:
  - clientSideWeightedRoundRobinPolicy:
      blackoutPeriod: 10s
      errorUtilizationPenalty: '0'
      weightExpirationPeriod: 3m
      weightUpdatePeriod: 1s