apiVersion: portaltransporter.infrared.reddit.com/v1alpha1
kind: BackendLBPolicies
metadata:
  name: blbp-invalidpolicy
  namespace: default
spec:
  backendRef:
    group: 'example'
    kind: Service
    name: ingress-probe-responder-grpc
    version: v1
  supportedPolicies:
    - clientSideWeightedRoundRobinPolicy:
        blackoutPeriod: 10s                # Negative duration, likely invalid
        errorUtilizationPenalty: '999999'   # Possible unrealistic value
        weightExpirationPeriod: 3m
        weightUpdatePeriod: 1s