apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: grpcroute-cross-ns-no-refgrant
  namespace: default
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: portaltransporter
    port: 9091
  rules:
  - backendRefs:
      - name: real-backend
        namespace: other-namespace # <- must NOT exist or must lack a ReferenceGrant
        port: 9001